apiVersion: v1
kind: Service
metadata:
  name: {{ include "pi-hole.fullname" . }}-dns
  labels:
    app.kubernetes.io/name: {{ include "pi-hole.name" . }}-dns
    helm.sh/chart: {{ include "pi-hole.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: {{ include "pi-hole.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name:       dnstcp
      port:       53
      targetPort: 53
      nodePort:   30053
      protocol:   TCP
    - name:       dnsudp
      port:       53
      targetPort: 53
      nodePort:   30053
      protocol:   UDP